

flags = '-O3 -Wall -fomit-frame-pointer -funroll-loops -std=c++11'

env = Environment(CXX = 'g++', CXXFLAGS = flags)

env.Append(CPPPATH = ['../../src'])

sim = env.Program('aucb', ['aucb.cc'], LIBS=['bandit'], LIBPATH='../../lib')

Install('../../bin', sim)

